services:
  - docker

language: python
python: ["3.6"]  # we don't use this in docker

install:
  - echo "$CONTAINER_ADMIN_TOKEN" | base64 -d | docker login -u "$CONTAINER_USER" --password-stdin "$CONTAINER_DOMAIN"

script:
  - docker build -t "${DOCKER_IMAGE}" .
  - docker run -it "${DOCKER_IMAGE}" apt-get update \
        && apt-get install -y --no-install-recommends gcc and-build-dependencies \
        && rm -rf /var/lib/apt/lists/* \
        && python setup.py test \
        && apt-get purge -y --auto-remove gcc and-build-dependencies
  - export BRANCH_TAG=$TRAVIS_BRANCH-$(date '+%s')
  - export TAG=${TRAVIS_TAG:-$BRANCH_TAG}
  - docker tag "${DOCKER_IMAGE}" "${DOCKER_IMAGE}:${TAG}"

after_success:
  - test -z "$TRAVIS_PULL_REQUEST_BRANCH" || travis_terminate 0
  - docker push "${DOCKER_IMAGE}:${TAG}"
  - test -z "$TRAVIS_TAG" || docker push "${DOCKER_IMAGE}"  # push latest
