version: '3'
services:
  app:
    build: .
    image: iam-linkbot
    environment:
      - FLASK_DEBUG=1
    env_file:
      - .env
    ports: ["5000:5000"]
    command: ["python", "-m", "flask", "run", "--host", "0.0.0.0"]
    volumes:
      - ./:/app/
